-- Seed new categories: Soap, Hair Oil, Sunscreen
-- Run this after existing seeds

-- Insert new categories
INSERT INTO categories (slug, title, long_description, criteria_content)
VALUES 
  ('soap', 'Soap', 'Curated collection of clean, transparent soaps for healthy skin', NULL),
  ('hair_oil', 'Hair Oil', 'Premium Ayurvedic and botanical hair oils for scalp health', NULL),
  ('sunscreen', 'Sunscreen', 'Safe mineral and clean-filter sunscreens for Indian skin', NULL)
ON CONFLICT (slug) DO UPDATE SET 
  title = EXCLUDED.title,
  long_description = EXCLUDED.long_description;

-- =====================
-- SOAP PRODUCTS (5 products)
-- =====================

INSERT INTO products (slug, name, brand, category_slug, image_url, status, editorial_pick, safe_starting_point, score, score_version, last_reviewed_at, usage_pattern, price_tier, short_reason, why_recommended, pros, cons, ingredient_summary, certifications, excluded_ingredients)
VALUES 
  (
    'juicy-chemistry-tea-tree-neem-rosemary-soap',
    'Tea Tree, Neem and Rosemary Organic Soap',
    'Juicy Chemistry',
    'soap',
    '/images/products/TeaTreeRosemary_1024x1024.webp',
    'active',
    true,
    true,
    94,
    'v1',
    '2025-12-10',
    'daily_use',
    'mid_range',
    'EcoCert COSMOS Organic cold-process soap with neem + tea-tree for antimicrobial, acne-prone skin — fully ingredient-transparent; gentle, super-fatted formulation preserves glycerin and avoids synthetic preservatives.',
    ARRAY['EcoCert COSMOS Organic certified (third-party audited) and uses cold-process saponification — an anhydrous, super-fatted formula that preserves glycerin and avoids synthetic preservatives.', 'Formulation uses Neem, Tea Tree and Rosemary at meaningful concentrations for antimicrobial support; full INCI and manufacturing notes are published by the brand.', 'Anhydrous cold-process method and transparent supply chain reduce microbiological risk while delivering skin-friendly fatty acids appropriate for Indian conditions.', 'Dermatologically tested for safety and irritation; shelf life stated on product page (9 months from manufacture, 6 months after opening).'],
    ARRAY['EcoCert COSMOS Organic certification', 'Full INCI disclosure and cold-process formulation', 'Effective botanical antimicrobial synergy for acne-prone skin'],
    ARRAY['Shorter shelf-life than highly preserved commercial bars (requires dry storage)', 'May be softer in humid storage conditions'],
    'Sodium Oliviate (saponified olive oil), Sodium Cocoate (saponified coconut oil), Neem Leaf Extract (Azadirachta indica), Aqua, Sodium Shea Butterate (saponified shea butter), Sodium Mango Butterate (saponified mango butter), Sodium Castorate (saponified castor oil), Lavandula angustifolia (Lavender) Oil, Rosmarinus officinalis (Rosemary) Oil, Melaleuca alternifolia (Tea Tree) Oil.',
    ARRAY['EcoCert COSMOS Organic'],
    ARRAY['SLS', 'SLES', 'Parabens', 'Formaldehyde donors']
  ),
  (
    'soultree-healing-turmeric-tulsi-soap',
    'SoulTree Healing Soap Turmeric and Tulsi',
    'SoulTree',
    'soap',
    '/images/products/Soultree_healing_soap.jpg',
    'active',
    true,
    true,
    90,
    'v1',
    '2025-11-20',
    'daily_use',
    'mid_range',
    'BDIH Certified Natural formulation using turmeric and tulsi in a high-TFM vegetable-oil soap base — transparent INCI and mild formulation logic suited to sensitive skin.',
    ARRAY['Listed as Certified Natural by BDIH on retailer/brand pages — this enforces exclusion of many questionable synthetics and adds a third-party trust signal.', 'Brand publishes INCI and positions the soap as high-TFM / vegetable oil based with turmeric and tulsi for anti-inflammatory and antimicrobial benefits.', 'Product pages indicate absence of parabens and SLS/SLES and recommend it for sensitive, blemish-prone skin.'],
    ARRAY['BDIH / Certified Natural trust signal', 'Botanical actives with anti-inflammatory rationale (turmeric) and antimicrobial support (tulsi)', 'High-TFM / vegetable-oil soap base preserves glycerin and is gentle when used with proper user guidance'],
    ARRAY['May contain natural fragrance / essential oil allergens (check INCI for Linalool, Limonene)', 'Alkaline pH inherent to soap bars — users coming from syndet products may need a transition period'],
    'High-TFM vegetable oil soap base (saponified vegetable oils), Turmeric extract (Curcuma spp.), Tulsi (Ocimum sanctum) extract, glycerin, moisturizing vegetable oils/butters.',
    ARRAY['BDIH (Certified Natural)'],
    ARRAY['SLS', 'SLES', 'Parabens', 'Formaldehyde donors']
  ),
  (
    'rustic-art-lemon-charcoal-soap',
    'Lemon Charcoal Soap',
    'Rustic Art',
    'soap',
    '/images/products/RusticArt.jpg',
    'active',
    true,
    true,
    88,
    'v1',
    '2025-12-01',
    'daily_use',
    'mid_range',
    'Cold-process, high-TFM bar with activated charcoal and lemon for oil-control and gentle exfoliation; transparent ingredient practices and plastic-free packaging make it an eco-friendly everyday option.',
    ARRAY['Cold-process formulation using a balanced blend of hard and soft oils (coconut, castor, sunflower, rice bran, linseed, sesame, karanja, olive, hemp and kokum butter) that preserves glycerin and performs well in Indian water conditions.', 'Activated charcoal provides gentle adsorption of surface oil and impurities while lemon peel and lemongrass offer mild astringent and brightening action.', 'Brand publishes full ingredient disclosure and emphasizes sustainable, plastic-free packaging; product positioning and formulation match our non-negotiable exclusions.'],
    ARRAY['Good oil-control profile for oily/acne-prone skin', 'Cold-process preserves glycerin and yields high TFM benefits', 'Sustainable, plastic-free packaging'],
    ARRAY['Contains citrus-derived ingredients (lemon peel/oil) — potential sensitizer for very sensitive skin', 'As a true soap bar it is alkaline — users coming from syndet products may need a transition period'],
    'Organic Oils of Cocos nucifera (Coconut); Ricinus communis (Castor); Helianthus annuus (Sunflower); Oryza sativa bran (Rice bran); Linum usitatissimum (Linseed); Sesamum indicum (Sesame); Pongamia glabra (Karanja); Olea europaea (Olive); Cannabis sativa (Hemp Oil); Garcinia indica (Kokum) Butter; Activated Charcoal; Citrus medica limonum (Lemon) Peel Powder; Cymbopogon schoenanthus (Lemongrass) Oil.',
    ARRAY[]::text[],
    ARRAY['SLS', 'SLES', 'Parabens', 'Formaldehyde donors']
  ),
  (
    'vilvah-classic-goat-milk-soap',
    'Classic Goat Milk Soap',
    'Vilvah',
    'soap',
    '/images/products/VilvahGoatMilk.webp',
    'active',
    false,
    true,
    87,
    'v1',
    '2025-11-30',
    'daily_use',
    'mid_range',
    'Handmade cold-processed goat-milk soap with a high-TFM vegetable oil base; farm-fresh goat milk and emollient oils support moisturization and barrier repair while preserving glycerin.',
    ARRAY['Vilvah documents the product as a cold-processed goat-milk soap made with farm-fresh goat milk — ideal for dry and sensitive skin.', 'Ingredient analysis (INCI) shows key emollients: Extra-virgin olive oil, coconut oil and castor oil; these provide a high-TFM profile and help retain skin moisture.', 'Retail listing confirms product weight (125 g) and positioning for face and body; no organic claim is made on the retailer page.'],
    ARRAY['Excellent moisturizing profile (goat milk + olive/coconut oils)', 'Cold-processed method preserves natural glycerin and skin-friendly fatty acids', 'Good match for dry or sensitive skin when used with proper user guidance'],
    ARRAY['As a true soap bar it is alkaline — users switching from syndet products may need a transition period', 'Perishable in very humid storage if not kept dry (recommend dry dish)'],
    'Goat Milk; Olea Europaea (Extra Virgin Olive Oil); Cocos Nucifera (Coconut Oil); Ricinus Communis (Castor Oil); Lavandula Angustifolia (Lavender essential oil), Sodium Hydroxide (Lye).',
    ARRAY[]::text[],
    ARRAY['SLS', 'SLES', 'Parabens', 'Formaldehyde donors']
  ),
  (
    'kaprica-100pct-coconut-soap',
    '100 Percent Coconut Oil Soap Lavender and Tea Tree',
    'Kaprica Naturals',
    'soap',
    NULL,
    'active',
    false,
    true,
    85,
    'v1',
    '2025-10-15',
    'daily_use',
    'affordable',
    'Artisanal cold-pressed 100% coconut oil soap (Lavender and Tea Tree) with a high TFM around 80 for strong lather in hard water; simple INCI and no added preservatives/sulfates/parabens per brand listings.',
    ARRAY['Formulated from pure cold-pressed coconut oil (high lauric profile) producing strong lather and good rinsability in hard water — manufacturer-stated TFM around 80.', 'Minimalist INCI (cold-pressed coconut oil, vegan glycerin, Lavender and Tea Tree essential oils) reduces hidden additives and allergen vectors.', 'Brand and multiple retailers list the product as preservative-free and free from sulfates/parabens — aligns with our exclusion gate and makes it a safe starting point for many users.'],
    ARRAY['Excellent lather and rinsability in hard water due to high-lauric coconut oil', 'Very simple, short INCI list (low chemical complexity)', 'Affordable artisan option with clear product positioning'],
    ARRAY['Very cleansing (can be drying for extremely dry skin) — follow with a moisturizer', 'Contains essential oils (Lavender, Tea Tree) which may be sensitizers for some users'],
    'Pure Cold Pressed Coconut Oil (Cocos Nucifera), Vegan Glycerin, Lavandula angustifolia (Lavender) Essential Oil, Melaleuca alternifolia (Tea Tree) Essential Oil, Sodium Hydroxide (fully reacted).',
    ARRAY[]::text[],
    ARRAY['SLS', 'SLES', 'Parabens', 'Formaldehyde donors']
  )
ON CONFLICT (slug) DO UPDATE SET 
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category_slug = EXCLUDED.category_slug,
  image_url = EXCLUDED.image_url,
  status = EXCLUDED.status,
  editorial_pick = EXCLUDED.editorial_pick,
  safe_starting_point = EXCLUDED.safe_starting_point,
  score = EXCLUDED.score,
  last_reviewed_at = EXCLUDED.last_reviewed_at,
  usage_pattern = EXCLUDED.usage_pattern,
  price_tier = EXCLUDED.price_tier,
  short_reason = EXCLUDED.short_reason,
  why_recommended = EXCLUDED.why_recommended,
  pros = EXCLUDED.pros,
  cons = EXCLUDED.cons,
  ingredient_summary = EXCLUDED.ingredient_summary,
  certifications = EXCLUDED.certifications,
  excluded_ingredients = EXCLUDED.excluded_ingredients;

-- =====================
-- HAIR OIL PRODUCTS (10 products)
-- =====================

INSERT INTO products (slug, name, brand, category_slug, image_url, status, editorial_pick, safe_starting_point, score, score_version, last_reviewed_at, usage_pattern, price_tier, short_reason, why_recommended, pros, cons, ingredient_summary, certifications, excluded_ingredients)
VALUES 
  (
    'kama-ayurveda-bringadi-intensive-hair-treatment',
    'Bringadi Intensive Hair Treatment',
    'Kama Ayurveda',
    'hair_oil',
    '/images/products/kama_ayurvedha_brigandi_intensive_hair_oil.jpg',
    'active',
    true,
    false,
    96,
    'v1',
    '2026-01-04',
    'daily_use',
    'premium',
    'The gold standard of Ayurvedic hair care, using a 100% natural traditional base and extraction method.',
    ARRAY['Uses the traditional Kshir Pak Vidhi extraction method', 'Indigo and Bhringraj effectively manage early greying', 'Completely free of any chemical preservatives or synthetic scents'],
    ARRAY['Exceptional quality ingredients', 'Authentic clinical results'],
    ARRAY['High price point', 'Strong medicinal scent'],
    'Indigo, Bhringraj, Amla, Sesame Oil, Milk',
    ARRAY['100% Natural'],
    ARRAY['Mineral Oil', 'Synthetic Fragrance', 'Silicones', 'BHT', 'Artificial Colors']
  ),
  (
    'sesa-ayurvedic-hair-oil-traditional-gold',
    'Ayurvedic Hair Oil (Traditional Gold)',
    'Sesa',
    'hair_oil',
    '/images/products/sesa_ayurvedhic_hair_oil.jpg',
    'active',
    false,
    true,
    88,
    'v1',
    '2026-01-04',
    'daily_use',
    'affordable',
    'A budget-friendly legacy oil that maintains strict Ayurvedic integrity without mineral oils.',
    ARRAY['Boils 18 herbs in milk for 22 hours (Kshir Pak Vidhi)', 'Excellent value for a mineral-oil-free formula', 'Includes 5 essential oils for added scalp stimulation'],
    ARRAY['Very affordable', 'Time-tested formulation'],
    ARRAY['Texture is quite thick/heavy'],
    '18 Herbs (Bhringraj, Triphala), Milk, Sesame Oil, Coconut Oil',
    ARRAY['Ayurvedic Proprietary Medicine'],
    ARRAY['Mineral Oil', 'Parabens', 'BHT', 'Silicones']
  ),
  (
    'nat-habit-daasabuti-hibiscus-amla-summer-oil',
    'Daasabuti Hibiscus Amla Summer Oil',
    'Nat Habit',
    'hair_oil',
    '/images/products/nat_habit_amla_hair_oil.jpg',
    'active',
    true,
    true,
    94,
    'v1',
    '2026-01-04',
    'daily_use',
    'mid_range',
    'Freshly prepared oil using whole flowers and leaves with zero chemical shelf-life extenders.',
    ARRAY['Made fresh in Ayurvedic kitchens and shipped within days', 'Infused with fresh Hibiscus flowers for natural conditioning', 'Zero preservatives; purely plant-based stability'],
    ARRAY['Very fresh feel', 'Non-greasy penetration'],
    ARRAY['Shorter shelf life (uses no preservatives)'],
    'Fresh Hibiscus, Amla, Curry Leaves, Coconut Oil, Castor Oil',
    ARRAY['100% Fresh Botanical'],
    ARRAY['Mineral Oil', 'Fragrance', 'BHT', 'Preservatives']
  ),
  (
    'avimee-herbal-keshpallav-hair-oil',
    'Keshpallav Hair Oil',
    'Avimee Herbal',
    'hair_oil',
    '/images/products/avimee_herbal_hair_oil.jpg',
    'active',
    true,
    true,
    92,
    'v1',
    '2026-01-04',
    'daily_use',
    'mid_range',
    'A high-potency blend of 50+ herbs and cold-pressed oils focusing on modern scalp nutrition.',
    ARRAY['Contains Rosemary oil which is a proven circulation booster', 'Uses a complex variety of 50+ herbs for multi-action care', 'Extremely transparent about the lack of fillers'],
    ARRAY['Highly concentrated', 'Excellent for hair fall'],
    ARRAY['Lighter scent might not feel traditional to some'],
    'Rosemary Oil, Kalonji, Amla, Bhringraj, Seed Oil Blend',
    ARRAY[]::text[],
    ARRAY['Mineral Oil', 'Silicones', 'Artificial Fragrance', 'Parabens']
  ),
  (
    'blue-nectar-briganantadi-hair-repair-treatment',
    'Briganantadi Hair Repair and Treatment',
    'Blue Nectar',
    'hair_oil',
    '/images/products/blue_nectar_hair_oil.jpg',
    'active',
    false,
    true,
    89,
    'v1',
    '2026-01-04',
    'daily_use',
    'premium',
    'A lighter, luxury Ayurvedic oil that focuses on aromatherapy and root-level repair.',
    ARRAY['Uses natural essential oils for a calming sensory experience', 'Rich in Bhringraj and Malkangani for follicle health', 'Superior glass packaging to prevent UV oxidation'],
    ARRAY['Pleasant natural aroma', 'Absorbs faster than traditional oils'],
    ARRAY['More expensive per ml than mass brands'],
    'Bhringraj, Rosemary, Lavender Oil, Sesame Oil, Coconut Oil',
    ARRAY['Ayurvedic Proprietary Medicine'],
    ARRAY['Mineral Oil', 'BHT', 'Synthetic Dyes', 'Phthalates']
  ),
  (
    'tribe-concepts-90-day-miracle-hair-oil',
    '90 Day Miracle Hair Oil',
    'The Tribe Concepts',
    'hair_oil',
    '/images/products/tribe_concepts_hair_oil.jpg',
    'active',
    true,
    false,
    93,
    'v1',
    '2026-01-04',
    'daily_use',
    'mid_range',
    'A minimalist, zero-chemical South Indian oil focused on long-term hair quality improvement.',
    ARRAY['Uses nutrient-dense Black Sesame oil as a base', 'No added fragrance; relies on the raw potency of the herbs', 'Eco-friendly tin packaging ensures no plastic leaching'],
    ARRAY['Visibly improves hair thickness', 'Eco-conscious packaging'],
    ARRAY['Earthy, raw scent is polarizing'],
    'Black Sesame Oil, Hibiscus, Amla, Indian Gooseberry',
    ARRAY['100% Chemical Free'],
    ARRAY['Mineral Oil', 'Fragrance', 'Parabens', 'Silicones']
  ),
  (
    'soulflower-rosemary-lavender-healthy-hair-oil',
    'Rosemary Lavender Healthy Hair Oil',
    'Soulflower',
    'hair_oil',
    '/images/products/soulflower_rosemary_hair_oil.jpg',
    'active',
    false,
    true,
    87,
    'v1',
    '2026-01-04',
    'daily_use',
    'affordable',
    'A simple but effective cold-pressed blend focused on essential oil therapy for the scalp.',
    ARRAY['Hexane-free extraction of all carrier oils', 'Rosemary and Lavender provide antimicrobial scalp protection', 'Rich in Jojoba and Castor for deep moisture'],
    ARRAY['Refreshing cooling sensation', 'Good value for volume'],
    ARRAY['Strong herbal/lavender aroma'],
    'Rosemary Essential Oil, Lavender Oil, Castor Oil, Jojoba Oil',
    ARRAY['ECOCERT Raw Ingredients'],
    ARRAY['Mineral Oil', 'Hexane', 'Artificial Fragrance', 'Synthetic Colors']
  ),
  (
    'indulekha-bringha-ayurvedic-oil',
    'Bringha Ayurvedic Oil',
    'Indulekha',
    'hair_oil',
    '/images/products/indulekha_hair_oil.jpg',
    'active',
    false,
    true,
    85,
    'v1',
    '2026-01-04',
    'daily_use',
    'affordable',
    'A clinically designed Ayurvedic medicine with a patented applicator for better scalp penetration.',
    ARRAY['Virgin Coconut Oil base for maximum shaft penetration', 'Proprietary Appli-comb ensures oil reaches roots without mess', 'High concentration of Bhringraj (Eclipta Alba)'],
    ARRAY['Mess-free applicator', 'Easy to find in stores'],
    ARRAY['Distinctive medicinal smell'],
    'Bhringraj, Svetakutaja, Amla, Virgin Coconut Oil',
    ARRAY['Ayurvedic Proprietary Medicine'],
    ARRAY['Mineral Oil', 'Synthetic Dyes', 'Artificial Perfume']
  ),
  (
    'rustic-art-deep-conditioning-hair-oil',
    'Deep Conditioning Hair Oil',
    'Rustic Art',
    'hair_oil',
    '/images/products/rustic_hair_oil.jpg',
    'active',
    false,
    true,
    91,
    'v1',
    '2026-01-04',
    'daily_use',
    'affordable',
    'A high-penetration oil using advanced plant lipids like Moringa and Avocado to deep-condition dry hair.',
    ARRAY['Uses Avocado oil which penetrates the hair cortex better than regular oils', '100% Vegan and Organic certified ingredients', 'Free of all synthetic stabilizers and silicone coatings'],
    ARRAY['Excellent for managing frizz', 'Ultra-clean ingredient list'],
    ARRAY['Standard bottle design (non-applicator)'],
    'Moringa Oil, Avocado Oil, Argan Oil, Flaxseed Oil',
    ARRAY['Organic', 'Vegan'],
    ARRAY['Mineral Oil', 'Silicones', 'Synthetic Scent', 'Parabens']
  ),
  (
    'khadi-natural-amla-bhringraj-powered-botanics',
    'Amla and Bhringraj (Powered Botanics)',
    'Khadi Natural',
    'hair_oil',
    '/images/products/khadi_natural_hair_oil.jpg',
    'active',
    false,
    true,
    84,
    'v1',
    '2026-01-04',
    'daily_use',
    'affordable',
    'The specific mineral-oil-free variant of Khadi famous Amla-Bhringraj blend.',
    ARRAY['Great starting point for those moving away from commercial paraffin oils', 'Uses a pure sesame and almond base for nutrition', 'Traditional Amla infusion for vitamin C and scalp health'],
    ARRAY['Very budget friendly', 'Widely available'],
    ARRAY['Must check label to ensure it is the Powered Botanics version'],
    'Amla, Bhringraj, Neem, Henna, Sesame Oil',
    ARRAY[]::text[],
    ARRAY['Mineral Oil', 'Silicones', 'Synthetic Fragrance', 'Parabens']
  )
ON CONFLICT (slug) DO UPDATE SET 
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category_slug = EXCLUDED.category_slug,
  image_url = EXCLUDED.image_url,
  status = EXCLUDED.status,
  editorial_pick = EXCLUDED.editorial_pick,
  safe_starting_point = EXCLUDED.safe_starting_point,
  score = EXCLUDED.score,
  last_reviewed_at = EXCLUDED.last_reviewed_at,
  usage_pattern = EXCLUDED.usage_pattern,
  price_tier = EXCLUDED.price_tier,
  short_reason = EXCLUDED.short_reason,
  why_recommended = EXCLUDED.why_recommended,
  pros = EXCLUDED.pros,
  cons = EXCLUDED.cons,
  ingredient_summary = EXCLUDED.ingredient_summary,
  certifications = EXCLUDED.certifications,
  excluded_ingredients = EXCLUDED.excluded_ingredients;

-- =====================
-- SUNSCREEN PRODUCTS (10 products)
-- =====================

INSERT INTO products (slug, name, brand, category_slug, image_url, status, editorial_pick, safe_starting_point, score, score_version, last_reviewed_at, usage_pattern, price_tier, short_reason, why_recommended, pros, cons, ingredient_summary, certifications, excluded_ingredients)
VALUES 
  (
    'reequil-sheer-zinc-tinted-sunscreen',
    'Sheer Zinc Tinted Sunscreen (SPF 50 PA+++)',
    'Reequil',
    'sunscreen',
    '/images/products/re_equil_sunscrren.jpg',
    'active',
    true,
    true,
    95,
    'v1',
    '2026-01-04',
    'daily_use',
    'mid_range',
    'A high-performance 100% mineral shield with a universal tint to prevent blue-light induced pigmentation.',
    ARRAY['Uses 25% non-nano Zinc Oxide as the sole UV filter', 'Iron oxides in the tint provide essential protection against visible blue light', 'Completely free of Oxybenzone, OMC, and synthetic fragrances'],
    ARRAY['Zero white cast due to tint', 'Excellent for sensitive skin'],
    ARRAY['Thick texture requires patting to blend'],
    '25% Zinc Oxide, Physalis Angulata Extract, Vitamin E',
    ARRAY['Dermatologically Tested'],
    ARRAY['Oxybenzone', 'Octinoxate', 'Parabens', 'Fragrance']
  ),
  (
    'minimalist-spf-60-silymarin-sunscreen',
    'Minimalist SPF 60 PA++++ Sunscreen',
    'Minimalist',
    'sunscreen',
    '/images/products/minimalist_sunscreen.jpg',
    'active',
    true,
    true,
    92,
    'v1',
    '2026-01-04',
    'daily_use',
    'mid_range',
    'Uses next-gen photostable filters and antioxidants for an invisible, weightless finish.',
    ARRAY['Features Tinosorb S and Uvinul A Plus which do not disrupt hormones', 'Infused with Silymarin (Milk Thistle) to neutralize free radicals', 'Verified SPF 60 rating via independent third-party testing'],
    ARRAY['Completely invisible finish', 'Pregnancy and lactation safe'],
    ARRAY['May feel too light for extremely dry skin'],
    'Tinosorb S, Uvinul A Plus, Silymarin, Hyaluronic Acid',
    ARRAY['Clean Label Project'],
    ARRAY['Oxybenzone', 'Homosalate', 'Octinoxate', 'Fragrance']
  ),
  (
    'chosen-safescreen-marina-mineral-sunscreen',
    'Chosen Safescreen Marina (SPF 50+ PA++++)',
    'Chosen by Dermatology',
    'sunscreen',
    '/images/products/chosen_sunscreen.jpg',
    'active',
    true,
    false,
    97,
    'v1',
    '2026-01-04',
    'daily_use',
    'premium',
    'A medical-grade mineral sunscreen specifically optimized for India humid tropical climate.',
    ARRAY['Formulated to be bloodstream safe with zero systemic absorption', 'Tested for 4 hours of water and sweat resistance', 'Uses non-nano Zinc Oxide in a high-purity mineral base'],
    ARRAY['Superior humidity control', 'Strictly non-absorbed filters'],
    ARRAY['Premium price point'],
    'Non-Nano Zinc Oxide, Natural Clay, C15-19 Alkanes',
    ARRAY['ISO 24443 Tested', 'Reef Safe'],
    ARRAY['All Chemical Filters', 'Silicones', 'Fragrance']
  ),
  (
    'sunscoop-100-mineral-sunscreen',
    'SunScoop 100% Mineral Sunscreen (SPF 50 PA++++)',
    'SunScoop',
    'sunscreen',
    '/images/products/sun_scoop_sunscreen.jpg',
    'active',
    false,
    true,
    89,
    'v1',
    '2026-01-04',
    'daily_use',
    'affordable',
    'A gentle, creamy mineral lotion ideal for children and reactive skin barriers.',
    ARRAY['Paediatrician-approved formula for sensitive young skin', 'Contains Xylitol and Oat extract to soothe inflammation', 'Purely physical blocking with zero chemical penetration'],
    ARRAY['Very soothing on angry skin', 'Budget-friendly mineral option'],
    ARRAY['Slight white cast on darker skin tones'],
    'Zinc Oxide, Oat Kernel Extract, Xylitol, Ceramides',
    ARRAY['FDA Approved'],
    ARRAY['Oxybenzone', 'Parabens', 'Fragrance', 'Sulphates']
  ),
  (
    'la-shield-fisico-spf-50-matte-gel',
    'La Shield Fisico SPF 50+ PA+++',
    'Glenmark (La Shield)',
    'sunscreen',
    '/images/products/la_shield_sunscreen.jpg',
    'active',
    false,
    true,
    91,
    'v1',
    '2026-01-04',
    'daily_use',
    'mid_range',
    'A pharmacy-favorite mineral gel that stays put during heavy sweat and outdoor activity.',
    ARRAY['100% Micronized Zinc Oxide for transparent mineral protection', 'Completely free of preservatives and potential endocrine disruptors', 'High water resistance makes it suitable for swimming'],
    ARRAY['Sweat-proof', 'No medicinal or synthetic smell'],
    ARRAY['Heavy silicone feel'],
    '25% Micronized Zinc Oxide, Vitamin E, Alkyl Benzoate',
    ARRAY['Dermatologically Tested'],
    ARRAY['Parabens', 'Fragrance', 'Oxybenzone', 'Chemical Filters']
  ),
  (
    'gabit-100-mineral-sunscreen-prebiotics',
    'Gabit 100% Mineral Sunscreen (SPF 50 PA++++)',
    'Gabit',
    'sunscreen',
    '/images/products/gabit_sunscreen.jpg',
    'active',
    true,
    true,
    93,
    'v1',
    '2026-01-04',
    'daily_use',
    'affordable',
    'A skin-loving mineral sunscreen that uses prebiotics to nurture the skin natural ecosystem.',
    ARRAY['Powered by Prebiotics and Probiotics to improve the skin barrier', 'Contains superfoods like Ashwagandha and Amla for antioxidant support', 'Strictly excludes silicones and endocrine-disrupting filters'],
    ARRAY['Feels like a moisturizer', 'Nurtures skin microbiome'],
    ARRAY['Tint-free version may show on very deep skin tones'],
    'Zinc Oxide, Ashwagandha, Probiotics, Vitamin E, Oat Extract',
    ARRAY['FDA Approved'],
    ARRAY['Silicones', 'Mineral Oils', 'Fragrance', 'Parabens']
  ),
  (
    'rivela-dermascience-tinosorb-m-zinc-sunscreen',
    'Rivela Dermascience Tinosorb M + Zinc Oxide',
    'Cipla (Rivela)',
    'sunscreen',
    '/images/products/rivela_sunscreen.jpg',
    'active',
    false,
    true,
    88,
    'v1',
    '2026-01-04',
    'daily_use',
    'mid_range',
    'A clean hybrid sunscreen from Cipla that combines modern safe filters with botanical healing.',
    ARRAY['Combines Tinosorb M (safe organic filter) with Zinc and Titanium', 'Infused with Gotu Kola (Cica) and Green Tea to calm irritation', 'Pharmaceutical quality assurance from Cipla Health'],
    ARRAY['Acts as a smooth primer', 'Very soothing for redness'],
    ARRAY['Contains a mix of filters, not 100% mineral'],
    'Tinosorb M, Zinc Oxide, Gotu Kola, Green Tea Extract',
    ARRAY['Clinical Dermatology Tested'],
    ARRAY['Parabens', 'SLS', 'Mineral Oils']
  ),
  (
    'uv-doux-mineral-tinted-sunscreen-gel',
    'UV Doux Mineral Sunscreen Gel (SPF 50 PA+++)',
    'Brinton (UV Doux)',
    'sunscreen',
    '/images/products/uv_doux_sunscreen.jpg',
    'active',
    true,
    true,
    94,
    'v1',
    '2026-01-04',
    'daily_use',
    'mid_range',
    'A water-free mineral gel that provides a weightless matte finish while preventing clogged pores.',
    ARRAY['Water-free (anhydrous) formula naturally resists bacterial growth', '100% Mineral filters with a subtle tint to neutralize white cast', 'Clinically proven non-acnegenic and hypoallergenic'],
    ARRAY['True matte finish', 'Will not sting eyes'],
    ARRAY['Gel texture can feel pasty if over-applied'],
    'Zinc Oxide, Titanium Dioxide, Vitamin E',
    ARRAY['Non-Comedogenic Certified'],
    ARRAY['Water', 'Chemical Filters', 'Parabens', 'Fragrance']
  ),
  (
    'skininspired-kidscreen-mineral-sunscreen',
    'SkinInspired Kidscreen (SPF 50+ PA++++)',
    'SkinInspired',
    'sunscreen',
    '/images/products/kidscreen_sunscreen.jpg',
    'active',
    true,
    true,
    96,
    'v1',
    '2026-01-04',
    'daily_use',
    'premium',
    'The highest safety standard for pediatric and eczema-prone skin, using US FDA-approved safe ingredients.',
    ARRAY['Uses 25% non-nano Zinc Oxide (ZinClear IM) for top-tier safety', 'Packaged in airless pumps to prevent oxidation and contamination', 'Enriched with Pro-Vitamin B5 and Vitamin E to soothe delicate skin'],
    ARRAY['Airless packaging', 'Pediatrician approved'],
    ARRAY['Higher price than standard kids sunscreens'],
    '25% Non-Nano Zinc Oxide, Pro-Vitamin B5, Vitamin E',
    ARRAY['Vegan', 'Cruelty Free'],
    ARRAY['Fragrance', 'Chemical Filters', 'Parabens', 'Essential Oils']
  ),
  (
    'dr-sheths-vitamin-c-ceramide-mineral-sunscreen',
    'Vitamin C and Ceramide Mineral Sunscreen',
    'Dr Sheths',
    'sunscreen',
    '/images/products/sheth_sunscreen.jpg',
    'active',
    false,
    true,
    90,
    'v1',
    '2026-01-04',
    'daily_use',
    'affordable',
    'A hydrating mineral sunscreen that repairs the skin barrier while adding a natural glow.',
    ARRAY['Ceramides strengthen the skin barrier against environmental heat', 'Vitamin C helps fade sunspots and boosts overall radiance', 'Specifically formulated for the hydration needs of Indian skin'],
    ARRAY['Moisturizing finish', 'No white cast for a mineral paste'],
    ARRAY['Not water-resistant; requires frequent reapplication if sweating'],
    'Zinc Oxide, Titanium Dioxide, Ceramides, Vitamin C',
    ARRAY['Dermatologically Tested'],
    ARRAY['Oxybenzone', 'Fragrance', 'Parabens']
  )
ON CONFLICT (slug) DO UPDATE SET 
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category_slug = EXCLUDED.category_slug,
  image_url = EXCLUDED.image_url,
  status = EXCLUDED.status,
  editorial_pick = EXCLUDED.editorial_pick,
  safe_starting_point = EXCLUDED.safe_starting_point,
  score = EXCLUDED.score,
  last_reviewed_at = EXCLUDED.last_reviewed_at,
  usage_pattern = EXCLUDED.usage_pattern,
  price_tier = EXCLUDED.price_tier,
  short_reason = EXCLUDED.short_reason,
  why_recommended = EXCLUDED.why_recommended,
  pros = EXCLUDED.pros,
  cons = EXCLUDED.cons,
  ingredient_summary = EXCLUDED.ingredient_summary,
  certifications = EXCLUDED.certifications,
  excluded_ingredients = EXCLUDED.excluded_ingredients;
